// ─────────────────────────────────────────────
// SAMPLE DATA — Cancer Research Day 2026
//
// This data is used when config.js has use_sample_data: true.
// In production, data loads live from your Google Sheet.
//
// GOOGLE SHEET COLUMN ORDER (must match exactly, row 1 headers):
// id | name | role | year | department | poster_number |
// title | summary | disease_area | research_program |
// clinical_input | linkedin_url | photo_url | email
// ─────────────────────────────────────────────

const SAMPLE_DATA = [
  {
    id: "cbg-001",
    name: "Sarah Chen",
    role: "PhD Student",
    year: "Year 2",
    department: "Cancer Biology & Genomics (CBG) — PIBBS",
    poster_number: "A-04",
    title: "Tumor microenvironment remodeling in triple-negative breast cancer",
    summary: "Investigating how immune cell composition in the tumor microenvironment shifts during neoadjuvant chemotherapy in TNBC, with the goal of identifying predictors of pathologic complete response.",
    disease_area: "Breast",
    research_program: "Tumor Immunology & Microenvironment",
    clinical_input: true,
    linkedin_url: "https://linkedin.com/in/sarahchen",
    photo_url: "",
    email: ""
  },
  {
    id: "cbg-002",
    name: "Marcus Webb",
    role: "PhD Student",
    year: "Year 3",
    department: "Cancer Biology & Genomics (CBG) — PIBBS",
    poster_number: "B-11",
    title: "Mechanisms of acquired resistance to KRAS G12C inhibitors in colorectal cancer",
    summary: "Using patient-derived organoids and proteomic profiling to map resistance mechanisms to sotorasib and adagrasib in KRAS G12C-mutant CRC, with a focus on bypass signaling through EGFR.",
    disease_area: "GI / Colorectal",
    research_program: "Cancer Biology & Genomics",
    clinical_input: true,
    linkedin_url: "",
    photo_url: "",
    email: ""
  },
  {
    id: "cbg-003",
    name: "Priya Nair",
    role: "PhD Student",
    year: "Year 2",
    department: "Cancer Biology & Genomics (CBG) — PIBBS",
    poster_number: "C-07",
    title: "PD-L1 regulation and immune evasion in castration-resistant prostate cancer",
    summary: "Characterizing transcriptional mechanisms that upregulate PD-L1 expression in CRPC following androgen deprivation therapy, and evaluating combination IO strategies in preclinical models.",
    disease_area: "GU / Prostate",
    research_program: "Tumor Immunology & Microenvironment",
    clinical_input: true,
    linkedin_url: "https://linkedin.com/in/priyanair",
    photo_url: "",
    email: ""
  },
  {
    id: "cbg-004",
    name: "James Okonkwo",
    role: "PhD Student",
    year: "Year 4",
    department: "Cancer Biology & Genomics (CBG) — PIBBS",
    poster_number: "A-12",
    title: "Epigenetic reprogramming drives AML relapse after venetoclax-based therapy",
    summary: "Single-cell ATAC-seq and RNA-seq of paired diagnosis/relapse AML samples to identify chromatin accessibility changes that enable leukemic stem cell survival under venetoclax + azacitidine.",
    disease_area: "Hematologic",
    research_program: "Epigenetic Regulation in Cancer",
    clinical_input: true,
    linkedin_url: "",
    photo_url: "",
    email: ""
  },
  {
    id: "cbg-005",
    name: "Yuki Tanaka",
    role: "PhD Student",
    year: "Year 2",
    department: "Cancer Biology & Genomics (CBG) — PIBBS",
    poster_number: "D-03",
    title: "HER2 intratumoral heterogeneity and response to T-DM1 in gastric adenocarcinoma",
    summary: "Spatial transcriptomics of HER2-positive gastric tumors to map heterogeneity patterns and correlate with clinical response to trastuzumab emtansine in a retrospective cohort.",
    disease_area: "GI / Colorectal",
    research_program: "Cancer Biology & Genomics",
    clinical_input: false,
    linkedin_url: "",
    photo_url: "",
    email: ""
  },
  {
    id: "cbg-006",
    name: "Aisha Osei",
    role: "PhD Student",
    year: "Year 3",
    department: "Cancer Biology & Genomics (CBG) — PIBBS",
    poster_number: "B-08",
    title: "Mismatch repair deficiency as a predictive biomarker in endometrial cancer",
    summary: "Functional characterization of MMR-deficient endometrial tumors and correlation with pembrolizumab response, using TCGA data and a prospective USC Norris patient cohort.",
    disease_area: "Multiple / Other",
    research_program: "Cancer Biology & Genomics",
    clinical_input: true,
    linkedin_url: "",
    photo_url: "",
    email: ""
  },
  {
    id: "cbg-007",
    name: "Luis Morales",
    role: "PhD Student",
    year: "Year 3",
    department: "Cancer Biology & Genomics (CBG) — PIBBS",
    poster_number: "C-14",
    title: "CAR-T cell persistence and exhaustion in B-cell lymphoma",
    summary: "Interrogating T cell exhaustion trajectories in axicabtagene ciloleucel-treated DLBCL patients using single-cell sequencing of pre- and post-infusion products collected at USC Norris.",
    disease_area: "Hematologic",
    research_program: "Tumor Immunology & Microenvironment",
    clinical_input: true,
    linkedin_url: "https://linkedin.com/in/luismorales",
    photo_url: "",
    email: ""
  },
  {
    id: "cbg-008",
    name: "Nina Petrov",
    role: "PhD Student",
    year: "Year 2",
    department: "Infectious Diseases, Immunology & Pathogenesis — PIBBS",
    poster_number: "D-09",
    title: "Oncolytic virus engineering for solid tumor immunotherapy",
    summary: "Engineering VSV-based oncolytic vectors with enhanced tumor selectivity and immunostimulatory payloads, assessed in syngeneic murine models of pancreatic and lung cancer.",
    disease_area: "Multiple / Other",
    research_program: "Tumor Immunology & Microenvironment",
    clinical_input: true,
    linkedin_url: "",
    photo_url: "",
    email: ""
  },
  {
    id: "pphs-001",
    name: "David Reyes",
    role: "PhD Student",
    year: "Year 3",
    department: "Epidemiology — PPHS",
    poster_number: "E-06",
    title: "Neighborhood disadvantage and cancer stage at diagnosis in Los Angeles County",
    summary: "Using linked SEER-Medicare and Census data to quantify how neighborhood-level social deprivation index predicts late-stage diagnosis across breast, colorectal, and lung cancers in LA County residents.",
    disease_area: "Cancer Prevention",
    research_program: "Cancer Epidemiology",
    clinical_input: false,
    linkedin_url: "",
    photo_url: "",
    email: ""
  },
  {
    id: "pphs-002",
    name: "Amara Jackson",
    role: "PhD Student",
    year: "Year 2",
    department: "Health Behavior Research — PPHS",
    poster_number: "E-11",
    title: "Culturally tailored cancer screening messaging for Black women in South LA",
    summary: "A mixed-methods study developing and piloting culturally adapted mHealth interventions to increase breast and cervical cancer screening uptake in underserved Black communities in South Los Angeles.",
    disease_area: "Cancer Prevention",
    research_program: "Cancer Health Disparities",
    clinical_input: true,
    linkedin_url: "",
    photo_url: "",
    email: ""
  },
  {
    id: "ms-001",
    name: "Kevin Park",
    role: "Master's Student",
    year: "Year 1",
    department: "Translational Biotechnology (MS)",
    poster_number: "F-02",
    title: "Nanoparticle drug delivery platforms for targeted pancreatic cancer therapy",
    summary: "Developing lipid nanoparticle formulations conjugated to EGFR-targeting peptides for enhanced drug delivery to pancreatic ductal adenocarcinoma in vitro and in xenograft models.",
    disease_area: "GI / Colorectal",
    research_program: "Translational & Clinical Sciences",
    clinical_input: false,
    linkedin_url: "",
    photo_url: "",
    email: ""
  },
  {
    id: "fellow-001",
    name: "Dr. Alicia Reyes",
    role: "Clinical Fellow / Resident",
    year: "Year 2",
    department: "Medical Oncology Fellowship",
    poster_number: "G-01",
    title: "Immune-related adverse event patterns in metastatic RCC treated with IO combinations",
    summary: "Retrospective chart review of 84 patients with mRCC treated with nivolumab + ipilimumab at USC Norris, characterizing irAE frequency, grade, management, and impact on treatment continuation.",
    disease_area: "GU / Prostate",
    research_program: "Translational & Clinical Sciences",
    clinical_input: false,
    linkedin_url: "https://linkedin.com/in/aliciareyes",
    photo_url: "",
    email: ""
  },
  {
    id: "fellow-002",
    name: "Dr. Daniel Kim",
    role: "Clinical Fellow / Resident",
    year: "Year 1",
    department: "Medical Oncology Fellowship",
    poster_number: "G-02",
    title: "Treatment sequencing after FOLFOX progression in metastatic CRC: practice patterns at LAC+USC",
    summary: "Retrospective cohort examining second-line treatment selection and outcomes for mCRC patients at LAC+USC between 2019 and 2024, with attention to RAS/BRAF mutational status and access disparities.",
    disease_area: "GI / Colorectal",
    research_program: "Translational & Clinical Sciences",
    clinical_input: false,
    linkedin_url: "",
    photo_url: "",
    email: ""
  },
  {
    id: "fellow-003",
    name: "Dr. Fatima Al-Hassan",
    role: "Clinical Fellow / Resident",
    year: "Year 2",
    department: "Hematology/Oncology Fellowship",
    poster_number: "G-03",
    title: "Outcomes of CAR-T therapy in relapsed/refractory DLBCL: real-world data from USC Norris",
    summary: "Single-center retrospective analysis of 41 patients with R/R DLBCL who received commercial CAR-T products, examining response rates, toxicity, and predictors of durable remission.",
    disease_area: "Hematologic",
    research_program: "Translational & Clinical Sciences",
    clinical_input: false,
    linkedin_url: "",
    photo_url: "",
    email: ""
  },
  {
    id: "postdoc-001",
    name: "Dr. Hiroshi Yamamoto",
    role: "Postdoctoral Fellow",
    year: "",
    department: "Tumor Immunology & Microenvironment",
    poster_number: "H-04",
    title: "Tertiary lymphoid structures as predictors of immunotherapy response in NSCLC",
    summary: "Multiplex immunofluorescence analysis of TLS density and maturation status in pre-treatment NSCLC biopsies from patients subsequently treated with anti-PD-1, correlating spatial immune architecture with clinical outcomes.",
    disease_area: "Lung",
    research_program: "Tumor Immunology & Microenvironment",
    clinical_input: true,
    linkedin_url: "",
    photo_url: "",
    email: ""
  },
  {
    id: "postdoc-002",
    name: "Dr. Sofia Mendez",
    role: "Postdoctoral Fellow",
    year: "",
    department: "Epigenetic Regulation in Cancer",
    poster_number: "H-07",
    title: "DNMT3A mutations shape chromatin accessibility in clonal hematopoiesis and AML progression",
    summary: "Using ATAC-seq and CUT&RUN in patient-derived samples and isogenic cell lines to map how DNMT3A loss-of-function alters the epigenetic landscape during the clonal hematopoiesis to AML transition.",
    disease_area: "Hematologic",
    research_program: "Epigenetic Regulation in Cancer",
    clinical_input: false,
    linkedin_url: "",
    photo_url: "",
    email: ""
  },
  {
    id: "fac-001",
    name: "Dr. Evanthia Roussos Torres",
    role: "Faculty",
    year: "",
    department: "Division of Medical Oncology",
    poster_number: "",
    title: "CRTEC: building the physician-scientist pipeline at USC Norris",
    summary: "Overview of CRTEC's training infrastructure, current programs, and the Translating Together pilot — connecting oncology fellows and CBG doctoral students through structured translational consultation.",
    disease_area: "Multiple / Other",
    research_program: "Translational & Clinical Sciences",
    clinical_input: false,
    linkedin_url: "",
    photo_url: "",
    email: ""
  },
  {
    id: "fac-002",
    name: "Dr. Josh Neman-Ebrahim",
    role: "Faculty",
    year: "",
    department: "Division of Medical Oncology",
    poster_number: "I-01",
    title: "Neural regulation of cancer progression in glioblastoma",
    summary: "Investigating how neurotransmitter signaling and neural circuitry interact with GBM tumor biology to drive invasion and therapy resistance, with translational implications for combining neuro-oncology and immunotherapy.",
    disease_area: "Neuro-oncology",
    research_program: "Translational & Clinical Sciences",
    clinical_input: false,
    linkedin_url: "",
    photo_url: "",
    email: ""
  },
  {
    id: "comm-001",
    name: "Maria Torres",
    role: "Community Member",
    year: "",
    department: "USC Norris Community Advisory Board",
    poster_number: "J-01",
    title: "Patient perspectives on clinical trial participation in South LA communities",
    summary: "Qualitative research capturing barriers to and facilitators of clinical trial enrollment among cancer patients in underserved South Los Angeles communities, with implications for trial design and outreach.",
    disease_area: "Cancer Prevention",
    research_program: "Community Outreach & Engagement",
    clinical_input: false,
    linkedin_url: "",
    photo_url: "",
    email: ""
  }
];
