// ─────────────────────────────────────────────
// CRD 2026 Directory — SAMPLE DATA (fallback)
// The live app pulls from your published Google Sheet (CONFIG.sheet_url).
// Column order matches CRD2026_Poster_Directory_Template.csv:
// id, name, role, year, department, poster_number, title, summary,
// disease_area, research_program, clinical_input, mentoring, linkedin_url, photo_url, email
// ─────────────────────────────────────────────
const SAMPLE_DATA = [
  {
    "id": "time-01",
    "name": "Sarah Chen",
    "role": "PhD Student",
    "year": "Year 2",
    "department": "Cancer Biology & Genomics (CBG) — PIBBS",
    "poster_number": "A-01",
    "title": "Tumor microenvironment remodeling in triple-negative breast cancer",
    "summary": "How stromal signaling reshapes the immune landscape of TNBC and creates resistance to checkpoint blockade.",
    "disease_area": "Breast",
    "research_program": "Tumor Immunology & Microenvironment (TIME)",
    "clinical_input": true,
    "mentoring": "",
    "linkedin_url": "https://linkedin.com/in/sarahchen-example",
    "photo_url": "",
    "email": "sarah.chen@usc.edu"
  },
  {
    "id": "time-02",
    "name": "Priya Nair",
    "role": "PhD Student",
    "year": "Year 2",
    "department": "Cancer Biology & Genomics (CBG) — PIBBS",
    "poster_number": "A-02",
    "title": "Macrophage polarization in the pancreatic tumor niche",
    "summary": "Single-cell profiling of tumor-associated macrophages and their role in immune exclusion in PDAC.",
    "disease_area": "GI/Colorectal",
    "research_program": "Tumor Immunology & Microenvironment (TIME)",
    "clinical_input": false,
    "mentoring": "",
    "linkedin_url": "",
    "photo_url": "",
    "email": ""
  },
  {
    "id": "time-03",
    "name": "Dr. Elena Vasquez",
    "role": "Faculty",
    "year": "",
    "department": "Division of Medical Oncology",
    "poster_number": "A-03",
    "title": "Combination immunotherapy in solid tumors",
    "summary": "Preclinical rationale and early-phase results for combining IO agents with targeted therapy.",
    "disease_area": "Other",
    "research_program": "Tumor Immunology & Microenvironment (TIME)",
    "clinical_input": true,
    "mentoring": "TRUE",
    "linkedin_url": "",
    "photo_url": "",
    "email": "elena.vasquez@med.usc.edu"
  },
  {
    "id": "time-04",
    "name": "Miguel Santos",
    "role": "Postdoctoral Fellow",
    "year": "",
    "department": "Keck School of Medicine",
    "poster_number": "A-04",
    "title": "A single-cell atlas of T-cell exhaustion in melanoma",
    "summary": "Mapping exhaustion trajectories across responders and non-responders to inform combination strategies.",
    "disease_area": "Melanoma/Skin",
    "research_program": "Tumor Immunology & Microenvironment (TIME)",
    "clinical_input": false,
    "mentoring": "",
    "linkedin_url": "",
    "photo_url": "",
    "email": ""
  },
  {
    "id": "erc-01",
    "name": "James Okonkwo",
    "role": "PhD Student",
    "year": "Year 4",
    "department": "Cancer Biology & Genomics (CBG) — PIBBS",
    "poster_number": "B-01",
    "title": "Epigenetic reprogramming drives AML relapse",
    "summary": "Chromatin state changes that let leukemic clones survive induction therapy and re-emerge.",
    "disease_area": "Leukemia",
    "research_program": "Epigenetic Regulation in Cancer (ERC)",
    "clinical_input": false,
    "mentoring": "",
    "linkedin_url": "",
    "photo_url": "",
    "email": "james.okonkwo@usc.edu"
  },
  {
    "id": "erc-02",
    "name": "Hannah Levine",
    "role": "PhD Student",
    "year": "Year 3",
    "department": "Cancer Biology & Genomics (CBG) — PIBBS",
    "poster_number": "B-02",
    "title": "Computational mapping of enhancer hijacking in neuroblastoma",
    "summary": "A machine-learning approach to detect oncogenic enhancer rewiring from whole-genome data.",
    "disease_area": "Pediatric",
    "research_program": "Epigenetic Regulation in Cancer (ERC)",
    "clinical_input": false,
    "mentoring": "",
    "linkedin_url": "",
    "photo_url": "",
    "email": ""
  },
  {
    "id": "erc-03",
    "name": "Dr. Robert Kim",
    "role": "Faculty",
    "year": "",
    "department": "Department of Biochemistry & Molecular Medicine",
    "poster_number": "B-03",
    "title": "DNA methylation clocks as early-detection biomarkers",
    "summary": "Blood-based methylation signatures that flag malignancy years before clinical presentation.",
    "disease_area": "Cancer care delivery/Implementation science",
    "research_program": "Epigenetic Regulation in Cancer (ERC)",
    "clinical_input": false,
    "mentoring": "TRUE",
    "linkedin_url": "",
    "photo_url": "",
    "email": ""
  },
  {
    "id": "tacs-01",
    "name": "Dr. Alicia Reyes",
    "role": "Clinical Fellow/Resident",
    "year": "Year 2",
    "department": "Medical Oncology Fellowship",
    "poster_number": "C-01",
    "title": "Immune-related adverse events in metastatic RCC on IO combinations",
    "summary": "Retrospective analysis of irAE frequency, grade, and management in 84 patients at USC Norris.",
    "disease_area": "Genitourinary",
    "research_program": "Translational and Clinical Sciences (TACS)",
    "clinical_input": true,
    "mentoring": "",
    "linkedin_url": "https://linkedin.com/in/aliciareyes-example",
    "photo_url": "",
    "email": "alicia.reyes@med.usc.edu"
  },
  {
    "id": "tacs-02",
    "name": "David Park",
    "role": "Clinical Fellow/Resident",
    "year": "Year 1",
    "department": "Hematology/Oncology Fellowship",
    "poster_number": "C-02",
    "title": "ctDNA dynamics as an early response marker in DLBCL",
    "summary": "Serial liquid biopsy to detect response and relapse ahead of imaging in aggressive lymphoma.",
    "disease_area": "Leukemia",
    "research_program": "Translational and Clinical Sciences (TACS)",
    "clinical_input": true,
    "mentoring": "",
    "linkedin_url": "",
    "photo_url": "",
    "email": ""
  },
  {
    "id": "tacs-03",
    "name": "Dr. Nadia Haddad",
    "role": "Faculty",
    "year": "",
    "department": "Division of Medical Oncology",
    "poster_number": "C-03",
    "title": "A machine-learning model predicting immunotherapy response from liquid biopsy",
    "summary": "Early-stage investigator project building an AI classifier for IO response using plasma multi-omics.",
    "disease_area": "Thoracic/Lung",
    "research_program": "Translational and Clinical Sciences (TACS)",
    "clinical_input": true,
    "mentoring": "TRUE",
    "linkedin_url": "",
    "photo_url": "",
    "email": ""
  },
  {
    "id": "tacs-04",
    "name": "Dr. Thomas Wright",
    "role": "Clinical Fellow/Resident",
    "year": "Year 3",
    "department": "Surgical Oncology",
    "poster_number": "C-04",
    "title": "Intraoperative margin assessment using AI-assisted imaging",
    "summary": "Real-time image analysis to reduce positive margins in breast-conserving surgery.",
    "disease_area": "Breast",
    "research_program": "Translational and Clinical Sciences (TACS)",
    "clinical_input": true,
    "mentoring": "",
    "linkedin_url": "",
    "photo_url": "",
    "email": ""
  },
  {
    "id": "ce-01",
    "name": "Grace Liu",
    "role": "PhD Student",
    "year": "Year 3",
    "department": "Population & Public Health Sciences (PPHS)",
    "poster_number": "D-01",
    "title": "Air pollution exposure and lung cancer incidence in LA County",
    "summary": "Linking long-term PM2.5 exposure to incidence patterns across catchment-area neighborhoods.",
    "disease_area": "Thoracic/Lung",
    "research_program": "Cancer Epidemiology (CE)",
    "clinical_input": false,
    "mentoring": "",
    "linkedin_url": "",
    "photo_url": "",
    "email": "grace.liu@usc.edu"
  },
  {
    "id": "ce-02",
    "name": "Dr. Ana Morales",
    "role": "Faculty",
    "year": "",
    "department": "Population & Public Health Sciences (PPHS)",
    "poster_number": "D-02",
    "title": "Environmental chemical mixtures and pediatric cancer risk",
    "summary": "A mixtures-modeling approach to prenatal exposures and childhood leukemia.",
    "disease_area": "Pediatric",
    "research_program": "Cancer Epidemiology (CE)",
    "clinical_input": false,
    "mentoring": "FALSE",
    "linkedin_url": "",
    "photo_url": "",
    "email": ""
  },
  {
    "id": "ce-03",
    "name": "Kevin Tran",
    "role": "Master's Student",
    "year": "",
    "department": "Translational Biotechnology (MS)",
    "poster_number": "D-03",
    "title": "Geospatial analysis of colorectal screening gaps",
    "summary": "Mapping under-screened areas in the catchment area to target outreach.",
    "disease_area": "GI/Colorectal",
    "research_program": "Cancer Epidemiology (CE)",
    "clinical_input": false,
    "mentoring": "",
    "linkedin_url": "",
    "photo_url": "",
    "email": ""
  },
  {
    "id": "ccr-01",
    "name": "Dr. Lourdes Ibarra",
    "role": "Faculty",
    "year": "",
    "department": "Population & Public Health Sciences (PPHS)",
    "poster_number": "E-01",
    "title": "Multilevel intervention to improve HPV vaccination in East LA",
    "summary": "A clinic- and community-level strategy tested across federally qualified health centers.",
    "disease_area": "Cancer care delivery/Implementation science",
    "research_program": "Cancer Control Research (CCR)",
    "clinical_input": false,
    "mentoring": "TRUE",
    "linkedin_url": "https://linkedin.com/in/lourdesibarra-example",
    "photo_url": "",
    "email": "lourdes.ibarra@usc.edu"
  },
  {
    "id": "ccr-02",
    "name": "Destiny Brooks",
    "role": "PhD Student",
    "year": "Year 2",
    "department": "Health Behavior Research — PPHS",
    "poster_number": "E-02",
    "title": "Financial toxicity and treatment adherence among survivors",
    "summary": "How out-of-pocket burden shapes adherence in a diverse survivor cohort.",
    "disease_area": "Other",
    "research_program": "Cancer Control Research (CCR)",
    "clinical_input": false,
    "mentoring": "",
    "linkedin_url": "",
    "photo_url": "",
    "email": ""
  },
  {
    "id": "ccr-03",
    "name": "Andre Flores",
    "role": "Undergraduate Student",
    "year": "Junior",
    "department": "USC Dornsife — Human Biology (MEDS 445)",
    "poster_number": "E-03",
    "title": "Summer project: mapping HPV vaccine uptake in East LA clinics",
    "summary": "Undergraduate cancer-prevention project; curious about graduate and MD-PhD paths.",
    "disease_area": "Cancer care delivery/Implementation science",
    "research_program": "Cancer Control Research (CCR)",
    "clinical_input": false,
    "mentoring": "",
    "linkedin_url": "",
    "photo_url": "",
    "email": ""
  },
  {
    "id": "coe-01",
    "name": "Maria Torres",
    "role": "Community Member",
    "year": "",
    "department": "USC Norris Community Advisory Board",
    "poster_number": "",
    "title": "Patient perspectives on clinical trial participation in South LA",
    "summary": "Qualitative work on barriers and facilitators to trial enrollment in underserved communities.",
    "disease_area": "Cancer care delivery/Implementation science",
    "research_program": "",
    "clinical_input": false,
    "mentoring": "",
    "linkedin_url": "",
    "photo_url": "",
    "email": ""
  },
  {
    "id": "coe-02",
    "name": "Denise Whitfield",
    "role": "Community Member",
    "year": "",
    "department": "Cancer Survivorship Advisory Council (CSAC)",
    "poster_number": "",
    "title": "Survivor-advocate — breast cancer",
    "summary": "Two-time breast cancer survivor and CSAC advocate joining the Patient Advocate poster walk. Ask me why plain language matters.",
    "disease_area": "Breast",
    "research_program": "",
    "clinical_input": false,
    "mentoring": "",
    "linkedin_url": "",
    "photo_url": "",
    "email": ""
  },
  {
    "id": "coe-03",
    "name": "Rosa Jimenez",
    "role": "Staff / Other",
    "year": "",
    "department": "Office of Community Outreach & Engagement",
    "poster_number": "",
    "title": "Promotores-led navigation: results from a community pilot",
    "summary": "A community health worker navigation model and its effect on screening completion.",
    "disease_area": "Cancer care delivery/Implementation science",
    "research_program": "",
    "clinical_input": false,
    "mentoring": "",
    "linkedin_url": "",
    "photo_url": "",
    "email": ""
  },
  {
    "id": "crtec-01",
    "name": "Aisha Mensah",
    "role": "Master's Student",
    "year": "",
    "department": "Translational Biotechnology (MS)",
    "poster_number": "E-04",
    "title": "Evaluating a near-peer mentoring model across CRTEC summer programs",
    "summary": "Mixed-methods evaluation of near-peer mentoring on trainee confidence and belonging.",
    "disease_area": "Other",
    "research_program": "Cancer Control Research (CCR)",
    "clinical_input": false,
    "mentoring": "",
    "linkedin_url": "",
    "photo_url": "",
    "email": ""
  },
  {
    "id": "crtec-02",
    "name": "Dr. Marcus Bell",
    "role": "Faculty",
    "year": "",
    "department": "CRTEC — Evaluation (CREATE)",
    "poster_number": "D-04",
    "title": "Building trainee tracking and mentor attribution for CCSG reporting",
    "summary": "A shared data model that links trainees to PIs and programs to support CCSG metrics.",
    "disease_area": "Other",
    "research_program": "Cancer Epidemiology (CE)",
    "clinical_input": false,
    "mentoring": "TRUE",
    "linkedin_url": "",
    "photo_url": "",
    "email": ""
  },
  {
    "id": "crtec-03",
    "name": "Tyler Nguyen",
    "role": "Postdoctoral Fellow",
    "year": "",
    "department": "T32 ADVANCE",
    "poster_number": "E-05",
    "title": "T32 ADVANCE: three-year trainee outcomes and publication metrics",
    "summary": "Outcomes from the ADVANCE training grant, including publications, transitions, and diversity.",
    "disease_area": "Other",
    "research_program": "Cancer Control Research (CCR)",
    "clinical_input": false,
    "mentoring": "",
    "linkedin_url": "",
    "photo_url": "",
    "email": ""
  },
  {
    "id": "sr-01",
    "name": "Dr. Wen Zhao",
    "role": "Faculty",
    "year": "",
    "department": "Genomics & Bioinformatics Shared Resource",
    "poster_number": "S-01",
    "title": "What the Genomics Core can run for your lab in under 2 weeks",
    "summary": "Live demo of bulk and single-cell RNA-seq turnaround, plus how to book time and what data you get back.",
    "disease_area": "Shared Resource/Core",
    "research_program": "Epigenetic Regulation in Cancer (ERC)",
    "clinical_input": false,
    "mentoring": "",
    "linkedin_url": "",
    "photo_url": "",
    "email": "wen.zhao@usc.edu"
  },
  {
    "id": "sr-02",
    "name": "Patricia Nguyen",
    "role": "Staff / Other",
    "year": "",
    "department": "Biostatistics Shared Resource",
    "poster_number": "S-02",
    "title": "Free 30-minute biostatistics consults — how to book",
    "summary": "An overview of study design and analysis support available to any USC Norris member, with sign-up on the spot.",
    "disease_area": "Shared Resource/Core",
    "research_program": "Cancer Epidemiology (CE)",
    "clinical_input": false,
    "mentoring": "",
    "linkedin_url": "",
    "photo_url": "",
    "email": "patricia.nguyen@usc.edu"
  }
];
